# Generated by Django 4.1 on 2023-07-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apple", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="words_bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(
                        default="", max_length=250, null=True, verbose_name="单词"
                    ),
                ),
                (
                    "pos",
                    models.CharField(
                        default="", max_length=250, null=True, verbose_name="词性"
                    ),
                ),
                (
                    "pt",
                    models.CharField(
                        default="", max_length=250, null=True, verbose_name="音标"
                    ),
                ),
                (
                    "pronunce_us",
                    models.CharField(
                        default="", max_length=250, null=True, verbose_name="美式发音"
                    ),
                ),
                (
                    "pronunce_uk",
                    models.CharField(
                        default="", max_length=250, null=True, verbose_name="英式发音"
                    ),
                ),
                (
                    "inflection",
                    models.CharField(
                        default="", max_length=250, null=True, verbose_name="变形式"
                    ),
                ),
                (
                    "sentence",
                    models.TextField(default="", null=True, verbose_name="例句"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Adjective",
        ),
        migrations.DeleteModel(
            name="Adverb",
        ),
        migrations.DeleteModel(
            name="Adverbial_fixation",
        ),
        migrations.DeleteModel(
            name="Categorydict",
        ),
        migrations.DeleteModel(
            name="fixedMatch",
        ),
        migrations.DeleteModel(
            name="Moun",
        ),
        migrations.DeleteModel(
            name="Nonverbpos",
        ),
        migrations.DeleteModel(
            name="Ordinal_Numeral",
        ),
        migrations.DeleteModel(
            name="Prep",
        ),
        migrations.DeleteModel(
            name="Pronoun",
        ),
        migrations.DeleteModel(
            name="Quantifierlemma",
        ),
        migrations.DeleteModel(
            name="Verbpluspos",
        ),
        migrations.DeleteModel(
            name="Verbpluspos_Double",
        ),
    ]
