# Generated by Django 4.1 on 2023-07-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apple", "0004_save_word"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Save_Word",
        ),
    ]
