# Generated by Django 4.1 on 2023-07-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apple", "0005_delete_save_word"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="words_bank",
            name="pt",
        ),
        migrations.AddField(
            model_name="words_bank",
            name="pt_uk",
            field=models.CharField(
                default="", max_length=250, null=True, verbose_name="英式音标"
            ),
        ),
        migrations.AddField(
            model_name="words_bank",
            name="pt_us",
            field=models.CharField(
                default="", max_length=250, null=True, verbose_name="美式音标"
            ),
        ),
    ]
