# Generated by Django 4.1 on 2023-07-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apple", "0006_remove_words_bank_pt_words_bank_pt_uk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="words_bank",
            name="pos",
            field=models.TextField(default="", null=True, verbose_name="词性"),
        ),
    ]
