# Generated by Django 4.1 on 2023-07-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apple", "0002_words_bank_delete_adjective_delete_adverb_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="European_Standard_Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(
                        default="", max_length=250, null=True, verbose_name="单词"
                    ),
                ),
                ("guideword", models.CharField(default="", max_length=250, null=True)),
                ("level", models.CharField(default="", max_length=250, null=True)),
                (
                    "part_of_speech",
                    models.CharField(default="", max_length=250, null=True),
                ),
                ("topic", models.CharField(default="", max_length=250, null=True)),
                (
                    "tag",
                    models.CharField(
                        default="", max_length=250, null=True, verbose_name="来源"
                    ),
                ),
            ],
        ),
    ]
